### ISSUE TITLE
Blank generated for token.immediate

### ISSUE THREAD

**Issue by aryx** [returntocorp/ocaml-tree-sitter-semgrep#270]
I tried importing tree-sitter-solidity but then got an error with:
```
        string: $ => choice(
            seq(
            '"',
            repeat(choice(
                token.immediate(prec(PREC.STRING, /[^"\\\n]+|\\\r?\n/)),
                $._escape_sequence
            )),
            '"'
            ),
            seq(
            "'",
            repeat(choice(
                token.immediate(prec(PREC.STRING, /[^'\\\n]+|\\\r?\n/)),
                $._escape_sequence
            )),
            "'"
            )
        ),

```
The issue seems to be the unnamed token.immediate parts.
If I create a named rule then it works, e.g. with
```
        string: $ => choice(
            seq(
            '"',
            repeat(choice(
                $._string_immediate_elt_inside_double_quote,
                $._escape_sequence
            )),
            '"'
            ),
            seq(
            "'",
            repeat(choice(
                $._string_immediate_elt_inside_quote,
                $._escape_sequence
            )),
            "'"
            )
        ),
	// We need to name those elts for ocaml-tree-sitter-semgrep
        _string_immediate_elt_inside_double_quote: $ =>
            token.immediate(prec(PREC.STRING, /[^"\\\n]+|\\\r?\n/)),
        _string_immediate_elt_inside_quote: $ =>
            token.immediate(prec(PREC.STRING, /[^'\\\n]+|\\\r?\n/)),

```
Not sure why we generate Blank in the first place and why we need to name those intermediate rules.

**Comment by aryx** [comment]
Here is the PR I had to do for reference: https://github.com/JoranHonig/tree-sitter-solidity/pull/18

**Comment by mjambon** [comment]
> The issue seems to be the unnamed token.immediate parts.
> If I create a named rule then it works

yes. Did you get a warning from ocaml-tree-sitter, an error, or nothing? I thought It was emitting a warning but I can't find by eyeballing the code. Anyway, the grammar needs to be modified if you need to recover the value or the location of the token. See below.

> Not sure why we generate Blank in the first place and why we need to name those intermediate rules.

It's because the tree-sitter parser doesn't return a token in these cases. Ocaml-tree-sitter used to extract those anonymous nodes into their own rules systematically but in some cases it doesn't work. It's complicated. It tries to do its best but in some cases we still end up with a parser that produces missing nodes (blanks). There are explanations in the source code of ocaml-tree-sitter-core, [Missing_node module](https://github.com/returntocorp/ocaml-tree-sitter-core/blob/main/src/gen/lib/Missing_node.mli).

The recommended solution is to change the grammar so as to have a named rule for each `token` (or `token.immediate`...) construct.

**Comment by aryx** [comment]
I got an error when I did ./test-lang solidity
I modified the grammar, see my referenced PR above.

**Comment by aryx** [comment]
Ok closing if it's complicated. Changing the grammar is not a big deal.
Maybe we could have a FAQ document that talks about that.
